inherit_from: rubocop-todo.yml

#- CocoaPods support for Ruby 1.8.7 ------------------------------------------#

HashSyntax:
  EnforcedStyle: hash_rockets

Lambda:
  Enabled: false

#- CocoaPods -----------------------------------------------------------------#

# We adopted raise instead of fail.
SignalException:
  EnforcedStyle: only_raise

# They are idiomatic
AssignmentInCondition:
  Enabled: false

# Allow backticks
AsciiComments:
  Enabled: false

# Indentation clarifies logic branches in implementations
IfUnlessModifier:
  Enabled: false

# No enforced convention here.
SingleLineBlockParams:
  Enabled: false

# Allow for `should.match /regexp/`.
AmbiguousRegexpLiteral:
  Exclude:
    - spec/**

# Allow `object.should == object` syntax.
Void:
  Exclude:
    - spec/**

ClassAndModuleChildren:
  Exclude:
    - spec/**

#- Trunk ---------------------------------------------------------------------#

ClassVars:
  Exclude:
    - spec/**

MultilineBlockChain:
  Exclude:
    - spec/**

# Variables are used for the erb templates
UselessAssignment:
  Enabled: false

