inherit_from: rubocop-todo.yml

#- CocoaPods -----------------------------------------------------------------#

# Can be removed once the support for Ruby 1.8.7 on CocoaPods.
HashSyntax:
  EnforcedStyle: hash_rockets

# We adopted raise instead of fail.
SignalException:
  EnforcedStyle: only_raise

# Allow backticks
AsciiComments:
  Enabled: false

# Allow for `should.match /regexp/`.
AmbiguousRegexpLiteral:
  Exclude:
    - spec/**

# Allow `object.should == object` syntax.
Void:
  Exclude:
    - spec/**

#- Trunk ---------------------------------------------------------------------#

ClassVars:
  Exclude:
    - spec/**

MultilineBlockChain:
  Exclude:
    - spec/**

# Variables are used for the erb templates
UselessAssignment:
  Enabled: false

