inherit_from: rubocop-todo.yml

#- CocoaPods -----------------------------------------------------------------#

# Can be removed once the support for Ruby 1.8.7 on CocoaPods.
HashSyntax:
  EnforcedStyle: hash_rockets

# We adopted raise instead of fail.
SignalException:
  EnforcedStyle: only_raise

# Allows for `should.match /regexp/`.
AmbiguousRegexpLiteral:
  Exclude:
    - spec/**

# Allow backticks
AsciiComments:
  Enabled: false

#- Trunk ---------------------------------------------------------------------#

ClassVars:
  Exclude:
    - spec/**

MultilineBlockChain:
  Exclude:
    - spec/**

