inherit_from: rubocop-todo.yml

# Remove once the support for Ruby 1.8.7 has been phased out
HashSyntax:
  EnforcedStyle: hash_rockets

# fail vs raise https://github.com/bbatsov/ruby-style-guide/issues/233
SignalException:
  EnforcedStyle: only_raise
