sudo: false
language: ruby
before_script:
- env RACK_ENV=test bundle exec rake db:bootstrap
install: bundle install --deployment --without development production
rvm: 2.1.3
cache: bundle
addons:
  postgresql: "9.4"
  apt:
    packages:
    - postgresql-server-dev-9.4